version: '3.8'

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3210:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
